name: Node.js CI

on:
  push:
    branches:
      - master
      - next
    paths-ignore:
      - 'bench/**'
      - 'examples/**'
  pull_request:
    branches:
      - master
      - next
    paths-ignore:
      - 'bench/**'
      - 'examples/**'

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [10, 12, 14, 16, 18]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 0.8.1

    - name: (env) cache
      uses: actions/cache@v3
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.nodejs }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-${{ matrix.nodejs }}-

    - name: Install
      run: |
        bun install
        bun add -g nyc
        bun add -g oxlint

    - name: Linter
      run: oxlint .

    - name: Test w/ Coverage
      run: nyc --include=packages bun run test

    - name: Report
      if: matrix.nodejs >= 18
      run: |
        nyc report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
